#Estágio build 1
FROM golang:1.17 AS builder

WORKDIR /go/src/app

COPY . .
#RUN go build fullcycle.go
#EXPOSE 3000

#CMD ["./fullcycle"]

#Estágio build 2
FROM golang:1.17-alpine
#nova pasta criada (public) só para diferenciar
WORKDIR /go/src/app
COPY --from=builder /go/src/app .

RUN go build fullcycle.go

EXPOSE 3000

CMD [ "./fullcycle" ]