#Estágio build 1
FROM golang:alpine AS builder

WORKDIR /go/src/app

COPY . .
# Using go get.
RUN go get -d -v
# Build the binary.
RUN go build fullcycle.go

#Estágio build 2
FROM scratch

WORKDIR /go/src/app
COPY --from=builder /go/src/app .

EXPOSE 3001

ENTRYPOINT ["/go/src/app"]
#CMD [ "./fullcycle" ]
